language: 
  - node_js

# Version number
node_js: 
  - 4.2.1 

build:
  ci: 
    - node --version

resources:
  - name: jatin-params
    type: params
    version:
      params:
        boo: foo
  
  - name: jatin-gitRepo
    type: gitRepo
    integration: github
    pointer:
      sourceName: jatindogra/sample_azure
      branch: master
 
  - name: oldGKEInt
    type: cliConfig
    integration: jatin-gke
    pointer:
      region: us-central1-a	

jobs:
  - name: runCLI-Job
    type: runCLI
    steps:
      - IN: jatin-params
      - IN: jatin-gitRepo
      - IN: oldGKEInt
      - TASK:
        - script: echo 'HI'
    
    
 
