language: 
  - node_js
runtime:
  nodePool: jatin-dynamic
# Version number
node_js: 
  - 4.2.1 
build:
  ci: 
    - printenv
    - echo $foo
    - echo $JATINPARAMSOUT_PARAMS_FOO
    - echo $JATINPARAMSIN_PARAMS_FOO
resources:
  - name: jatin-image
    type: image
    integration: jatin-docker
    pointer:
      sourceName: jatindogra/nginx
    seed:
      versionName: master

jobs:
  - name: jatin-manifest
    type: manifest
    
