language: 
  - node_js

# Version number
node_js: 
  - 4.2.1 

build:
  ci: 
    - node --version
    
jobs:
  - name: runSh-Job
    type: runSh
    steps:
      - TASK:
        - script: echo 'HI'
        
