language: 
  - node_js
runtime:
  nodePool: ubuntucustom
# Version number
node_js: 
  - 4.2.1 
build:
  ci: 
    - printenv
    - echo $foo
    - echo $JATINPARAMSOUT_PARAMS_FOO
    - shipctl get_resource_env jatin-params-in "PARAMS_FOO"

resources:
  - name: jatin-params-in
    type: params
    version:
      params:
        foo: boo
  
  - name: jatin-gitRepo
    type: gitRepo
    integration: github
    pointer:
      sourceName: jatindogra/sample_azure
      branch: master
 
  - name: jatin-params-out
    type: params
    version:
      params:
        foo: bar

jobs:
  - name: runSh-Job
    type: runSh
    runtime:
      nodePool: ubuntucustom
    steps:
      - IN: jatin-params-in
      - OUT: jatin-params-out
      - TASK:
        - script: shipctl get_resource_env jatin-params-in "PARAMS_FOO"
        - script: printenv
        - script: echo $foo
        - script: echo $JATINPARAMSOUT_PARAMS_FOO
        - script: shipctl get_resource_env jatin-params-out "PARAMS_FOO"
        
  - name: sample-repo_runCI
    type: runCI
    runtime:
      nodePool: ubuntucustom
    steps:
      - IN: jatin-params-in
      - OUT: jatin-params-out

