language: 
  - node_js

# Version number
node_js: 
  - 4.2.1 

build:
  ci: 
    - node --version

resources:
  - name: jatin-params-in
    type: params
    version:
      params:
        foo: boo
  
  - name: jatin-gitRepo
    type: gitRepo
    integration: github
    pointer:
      sourceName: jatindogra/sample_azure
      branch: master
 
  - name: jatin-params-out
    type: params
    version:
      params:
        foo: bar

jobs:
  - name: runSh-Job
    type: runSh
    runtime:		
      cluster: default-cluster
    steps:
      - IN: jatin-params-in
      - IN: jatin-gitRepo
      - TASK:
        - script: echo 'HI'
      - OUT: jatin-params-out
    
 
