language: 
  - node_js
runtime:
  nodePool: jatin-dynamic
# Version number
node_js: 
  - 4.2.1 
build:
  ci: 
    - printenv
    - echo $foo
    - echo $JATINPARAMSOUT_PARAMS_FOO
    - echo $JATINPARAMSIN_PARAMS_FOO
resources:
  - name: jatin-image
    type: image
    integration: jatin-docker
    pointer:
      sourceName: jatindogra/nginx
    seed:
      versionName: master
  
  - name: jatin-cluster
    type: cluster
    integration: jatin-aws
    pointer:
      region: "us-east-1"
      sourceName: my-cluster

jobs:
  - name: jatin-manifest
    type: manifest
    steps:
      - IN: jatin-image
      
  - name: jatin-deploy
    type: deploy
    steps:
      - IN: jatin-manifest
      
  - name: jatin-release
    type: release
    bump: major
    steps:
      - IN: jatin-manifest

