language: 
  - node_js

# Version number
node_js: 
  - 4.2.1 

build:
  ci: 
    - node --version

resources:
  - name: jatin-params
    type: params
    version:
      params:
        boo: foo

jobs:
  - name: runSh-Job
    type: runSh
    IN: jatin-params
    steps:
      - TASK:
        - script: echo "done"
    
 
