language: 
  - node_js

# Version number
node_js: 
  - 4.2.1 

build:
  ci: 
    - node --version

resources:
  - name: jatin-params
    type: params
    version:
      params:
        boo: foo
  
  - name: jatin-gitRepo
    type: gitRepo
    integration: github
    pointer:
      sourceName: jatindogra/sample_azure
      branch: master
 
  - name: oldpdr
    type: cliConfig
    integration: jatin-pdr

jobs:
  - name: runSh-Job
    type: runSh
    runtime:
      architecture: x86_64		
      os: Ubuntu_16.04
    steps:
      - IN: jatin-params
      - IN: jatin-gitRepo
      - IN: oldpdr
      - TASK:
        - script: echo 'HI'
    
    
 
