language: 
  - node_js
runtime:
  nodePool: default
# Version number
node_js: 
  - 4.2.1 
build:
  ci: 
    - printenv

resources:
  - name: jatin-img
    type: image
    integration: jatin-docker
    pointer:
      sourceName: "scriptnull/debian"
      isPull: false
    seed:
      versionName: "driftking"
  
  - name: jatin-kube
    type: cluster
    integration: jatin-kube
    versionTemplate:
      region: "us-central1-a"
      sourceName: jatin-cluster
      
  - name: jatin-version
    type: version
    versionTemplate:
      versionName: "0.0.1"
      
jobs:
  - name: jatin-manifest
    type: manifest
    steps:
      - IN: jatin-img
  
  - name: jatin-manifest-2
    type: manifest
    steps:
      - IN: jatin-img
 
  - name: jatin-deploy
    type: deploy
    steps:
      - IN: jatin-kube
      - IN: jatin-deploy-1
        force: true

  - name: jatin-deploy-1
    type: deploy
    steps:
      - IN: jatin-manifest
        force: true
      - IN: jatin-kube
  
  - name: jatin-release
    type: release
    steps:
      - IN: jatin-version
      - IN: jatin-manifest-2
  
  - name: jatin-deploy-2
    type: deploy
    steps:
      - IN: jatin-release
        force: true
      - IN: jatin-kube
