language: 
  - node_js

# Version number
node_js: 
  - 4.2.1

build:
  pre_ci:
    - echo "this is pr-ci"
  ci: 
    - node --version
    - echo "done"
    
resources:
  - name: jatin-params-master
    type: params
    version:
      params:
        boo: foo
  
  - name: jatin-gitRepo-master
    type: gitRepo
    integration: jatin-github
    pointer:
      sourceName: jatindogra/sample_azure
      branch: master

  - name: jatin-dockerOpts-master
    type: dockerOptions
    version:
      labels:
        foo: bar
        
  - name: jatin-state-master
    type: state

  - name: jatin-trigger-master
    type: trigger
    version:
      counter: 1

jobs:
  - name: sample-repo_runCI
    type: runCI
    steps:
      - IN: jatin-params-master
      - IN: jatin-gitRepo-master
      - IN: jatin-dockerOpts-master
      - IN: jatin-state-master
      - OUT: jatin-state-master
      - OUT: jatin-trigger-master
