language: 
  - node_js
runtime:
  nodePool: default
# Version number
node_js: 
  - 4.2.1 
build:
  ci: 
    - printenv

resources:
  - name: jatin-img
    type: image
    integration: jatin-docker
    pointer:
      sourceName: "scriptnull/debian"
      isPull: false
    seed:
      versionName: "driftking"
  
  - name: jatin-cluster
    type: cluster
    integration: jatin-cluster
    versionTemplate:
      region: "us-east-1"
      sourceName: jatin-cluster

jobs:
  - name: jatin-manifest
    type: manifest
    steps:
      - IN: jatin-img
        force: true
  
  - name: jatin-deploy
    type: deploy
    steps:
      - IN: jatin-manifest
      - IN: jatin-cluster
