language: 
  - node_js
runtime:
  nodePool: default
# Version number
node_js: 
  - 4.2.1 
build:
  ci: 
    - printenv
    - echo $foo
    - echo $JATINPARAMSOUT_PARAMS_FOO
    - echo $JATINPARAMSIN_PARAMS_FOO

jobs:
  - name: runSh-Job
    type: runSh
    allowPublicAccess: true
    steps:
      - TASK:
        - script: echo "done"
