language: 
  - node_js

# Version number
node_js: 
  - 4.2.1 

build:
  ci: 
    - node --version

resources:
  - name: jatin-params
    type: params
    version:
      params:
        boo: foo
  
  - name: jatin-gitRepo
    type: gitRepo
    integration: jatin-github
    pointer:
      sourceName: jatindogra/sample_azure
      branch: master
 
  - name: oldaws
    type: cliConfig
    integration: jatin-aws
    pointer:
      region: "us-east-1"
      
  - name: jatin-cluster
    type: cluster
    integration: jatin-aws
    pointer:
      region: "us-east-1"
      sourceName: my-cluster

  - name: jatin-dockerOpts
    type: dockerOptions
    version:
      labels:
        foo: bar
  
  - name: jatin-jfrog
    type: file
    integration: jatin-jfrog
    pointer:
      sourceName: none
    seed:
      versionName: none
 
  - name: jatin-image
    type: image
    integration: jatin-docker
    pointer:
      sourceName: jatindogra/nginx
    seed:
      versionName: master
  
  - name: jatin-integration
    type: integration
    integration: jatin-aws
  
  - name: jatin-slack
    type: integration
    integration: jatin-slack
    pointer:
      recipients:
        - "#local"
  
  - name: jatin-replicas
    type: replicas
    version:
      count: 1
  
  - name: jatin-state
    type: state
    
  - name: jatin-timeTrigger
    type: time
    seed:
      interval: "*/2 * * * *"
  
  - name: jatin-trigger
    type: trigger
    version:
      counter: 1
  
  - name: jatin-version
    type: version
    seed:
      versionName: "0.0.1"
    
jobs:
  - name: runSh-Job
    type: runSh
    steps:
      - IN: jatin-params
      - IN: jatin-gitRepo
      - IN: oldaws
      - IN: jatin-cluster
      - IN: jatin-dockerOpts
      - IN: jatin-jfrog
      - IN: jatin-image
      - IN: jatin-integration
      - IN: jatin-slack
      - IN: jatin-replicas
      - IN: jatin-state
      - IN: jatin-trigger
      - IN: jatin-version
      - TASK:
        - script: echo 'HI'

  - name: runSh-Job-Out
    type: runSh
    steps:
      - OUT: jatin-params
      - OUT: jatin-gitRepo
      - OUT: oldaws
      - OUT: jatin-cluster
      - OUT: jatin-dockerOpts
      - OUT: jatin-jfrog
      - OUT: jatin-image
      - OUT: jatin-integration
      - OUT: jatin-slack
      - OUT: jatin-replicas
      - OUT: jatin-state
      - OUT: jatin-version
      - TASK:
        - script: echo 'HI'
